/**
 * File-storage abstraction (SECURITY_PRINCIPLES.md §16). Callers work with a
 * server-generated opaque `key` and raw plaintext bytes; the backend owns WHERE
 * bytes live and whether they are encrypted at rest. This seam lets the local-disk
 * backend (encrypt-at-rest via AES-256-GCM) be swapped for S3 (server-side
 * encryption) later without touching the workers/documents module.
 *
 * The `key` is always generated by the caller as a random UUID — never derived
 * from client input — so there is no path-traversal / injection surface.
 */
export interface IFileStorage {
  /** Persist `data` under `key`, overwriting any existing object. */
  save(key: string, data: Buffer): Promise<void>;
  /** Read back the plaintext bytes previously saved under `key`. */
  read(key: string): Promise<Buffer>;
  /** Remove the object at `key`. A missing object is not an error (idempotent). */
  delete(key: string): Promise<void>;
}
